### ISSUE TITLE
check if binary_truth is numeric

### ISSUE THREAD

**Issue by mikelove** [markrobinsonuzh/iCOBRA#2]
If the binary_truth column is a logical, iCOBRA gives an error: 

```
 Error in approxfun(x.values.1, y.values.1, method = "constant", f = 1,  :
   zero non-NA points
 Calls: calculate_performance ... <Anonymous> -> .combine.performance.objects -> approxfun
```

If you could check to see if binary_truth is logical, and then convert to 0/1 internally, I think it would avoid this error.

**Comment by csoneson** [comment]
Thanks. This is fixed in 3995b901dece6600d979e667fde6f9ae5999fe32, logical `binary_truth` columns are now converted to numeric internally in `calculate_performance`
