### ISSUE TITLE
Unexpected legends?

### ISSUE THREAD

**Issue by koenvandenberge** [markrobinsonuzh/iCOBRA#6]
Hi @csoneson ,

It looks like `iCOBRA` seems to be returning unexpected legends in the latest (?) Bioconductor release. It seems to be showing different subgroups. This is also happening in the [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/iCOBRA/inst/doc/iCOBRA.html).

**Comment by csoneson** [comment]
Hi Koen - thanks for the report. Looks like the same issue as #3, #4 - the devel version of `ggplot2` should fix this (see #4) , but it looks like it's not yet on CRAN. I did implement a workaround in a branch in the meanwhile - I'll just merge it now and push to Bioc (both release and devel).

**Comment by koenvandenberge** [comment]
Thanks, and apologies for not having checked these closed issues.
